CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=10
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=1000
CONFIG_ZMK_SPLIT_BLE_PREF_INT=12
CONFIG_ZMK_SPLIT_BLE_PREF_LATENCY=10
CONFIG_ZMK_SPLIT_BLE_PREF_TIMEOUT=600
