BOOTMAGIC_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
LEADER_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LTO_ENABLE = yes
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = no
OLED_ENABLE = no
REPEAT_KEY_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
SPACE_CADET_ENABLE = no

ifneq ($(strip $(OPERATING_SYSTEM)),)
    OPT_DEFS += -DOPERATING_SYSTEM=$(OPERATING_SYSTEM)
endif

ifeq ($(strip $(RAZEN_CYGNUS_QMK)),yes)
    SERIAL_DRIVER = vendor
    OPT_DEFS += -DRAZEN_CYGNUS_QMK
endif
