CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=8
CONFIG_BT_PERIPHERAL_PREF_LATENCY=2
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=1000
CONFIG_BT_DATA_LEN_UPDATE=n

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=8
