#pragma once

#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 175
#define FLOW_TAP_TERM 100
#define PERMISSIVE_HOLD_PER_KEY
#define CHORDAL_HOLD
#define ONESHOT_TIMEOUT 1200
#define ONESHOT_TAP_TOGGLE 0

#define COMBO_TERM 30
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250
#define COMBO_TERM_PER_COMBO
#define COMBO_SHOULD_TRIGGER
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 16
#define MOUSEKEY_MAX_SPEED 8
#define MOUSEKEY_TIME_TO_MAX 40
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 16
#define MOUSEKEY_WHEEL_MAX_SPEED 4
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40

#ifdef RGB_MATRIX_ENABLE
#    define RGB_MATRIX_SLEEP
#    define RGB_MATRIX_KEYPRESSES
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#    define ENABLE_RGB_MATRIX_SOLID_SPLASH
#    define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#endif

#ifdef POINTING_DEVICE_ENABLE
#    define SPLIT_POINTING_ENABLE
#    define POINTING_DEVICE_RIGHT
#    define POINTING_DEVICE_TASK_THROTTLE_MS 1
#    define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#    define CIRQUE_PINNACLE_DIAMETER_MM 40
#    define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_2X
#    define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE
#    define CIRQUE_PINNACLE_TAP_ENABLE
#endif

#ifdef OLED_ENABLE
#    define OLED_TIMEOUT 120000
#endif
