BOOTMAGIC_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
GRAVE_ESC_ENABLE = no
I2C_DRIVER_REQUIRED = yes
KEY_OVERRIDE_ENABLE = no
LTO_ENABLE = yes
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = no
OLED_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
REPEAT_KEY_ENABLE = yes
# Aurora Sweep models per-key LEDs and underglow LEDs in RGB Matrix.
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
SPACE_CADET_ENABLE = no

ifneq ($(strip $(OPERATING_SYSTEM)),)
    OPT_DEFS += -DOPERATING_SYSTEM=$(OPERATING_SYSTEM)
endif
