BOOTMAGIC_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
LEADER_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LTO_ENABLE = yes
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = no
OLED_ENABLE = yes
REPEAT_KEY_ENABLE = yes
RGBLIGHT_ENABLE = yes
SPACE_CADET_ENABLE = no

ifneq ($(strip $(OPERATING_SYSTEM)),)
    OPT_DEFS += -DOPERATING_SYSTEM=$(OPERATING_SYSTEM)
endif
