draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  footer_text: ''
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  glyph_urls:
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    tabler: https://raw.githubusercontent.com/tabler/tabler-icons/master/icons/outline/{}.svg
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    '&sqt_dqt': {t: '''', s: '"'}
    '&colon_semi': {t: ':', s: ';'}
    '&dot_qmark': {t: '.', s: '?'}
    '&comma_excl': {t: ',', s: '!'}
    '&bspc_del': {t: '$$mdi:backspace$$', s: '$$mdi:backspace-reverse$$'}
    '&undo_redo': {t: '$$mdi:undo$$', s: '$$mdi:redo$$'}
    '&copy_cut': {t: '$$mdi:content-copy$$', s: '$$mdi:content-cut$$'}
    '&copy_paste': {t: '$$mdi:content-copy$$'}
    '&v_comma_excl': {t: ',', s: '!'}
    '&v_dot_qmark': {t: '.', s: '?'}
    '&adaptive_key': {t: '★'}
    '&adaptive_shift LSHFT 0': {t: '★', h: '$$mdi:arrow-up-bold$$'}
    '&adaptive_shift_ru LSHFT 0': {t: '★', h: '$$mdi:arrow-up-bold$$'}
    '&smart_shift LSHFT 0': {t: '★', h: '$$mdi:arrow-up-bold$$'}
    '&lt_esc LAYER_Nav ESC': {t: '$$mdi:keyboard-esc$$', h: Nav}
    '&lt_spc LAYER_Num 0': {t: Spc, s: Sentence, h: Num}
    '&lt_enter LAYER_Symbol RET': {t: '$$mdi:keyboard-return$$', h: Symbol}
    '&spc_morph': {t: Spc, s: Sentence}
    '&smart_mouse': Smart Mouse
    '&sl LAYER_Fn': {t: Fn}
    '&tog LAYER_Magic': {t: Magic, type: layer-activator}
    '&magic LAYER_Magic 0': {t: Magic, type: layer-activator}
    '&dot_spc': {t: '. ⇧'}
    '&dot_slash': {t: ./}
    '&triple_dot': {t: '...'}
    '&mkp LCLK': Left Click
    '&mkp RCLK': Right Click
    '&mkp MCLK': Middle Click
    '&mmv MOVE_UP': "Mouse ↑"
    '&mmv MOVE_DOWN': "Mouse ↓"
    '&mmv MOVE_LEFT': "Mouse ←"
    '&mmv MOVE_RIGHT': "Mouse →"
    '&msc SCRL_UP': "Scroll ↑"
    '&msc SCRL_DOWN': "Scroll ↓"
    '&msc SCRL_LEFT': "Scroll ←"
    '&msc SCRL_RIGHT': "Scroll →"
    '&bt_0': {t: BT 0}
    '&bt_1': {t: BT 1}
    '&bt_2': {t: BT 2}
    '&bt_3': {t: BT 3}
    '&lang_en': {t: EN}
    '&lang_ru': {t: RU}
    '&lang_ua': {t: UA}
    '&kp LA(LEFT)': {t: Page ←}
    '&kp LA(RIGHT)': {t: Page →}
    '&kp LC(LS(TAB))': {t: Tab ←}
    '&kp LC(TAB)': {t: Tab →}
    '&kp LC(Z)': {t: Undo}
    '&kp LC(LS(Z))': {t: Redo}
    '&kp LC(A)': {t: Tmux}
    '&kp LC(BSPC)': {t: Word ⌫}
    '&kp LC(DEL)': {t: Word ⌦}
    '&kp _SCR_AREA': {t: '$$mdi:crop$$', s: Scr}
    '&kp _SCR_FULL': {t: '$$mdi:monitor-screenshot$$', s: Scr}
    '&kp _SHUTDOWN': {t: '$$mdi:power$$'}
    '&kp LG(LC(LS(Q)))': {t: '$$mdi:power$$'}
    '&kp C_POWER': {t: '$$mdi:power$$'}
    '&kp K_POWER': {t: '$$mdi:power$$'}
    '&kp _LOCK': {t: '$$mdi:lock$$'}
    '&kp LG(LS(L))': {t: '$$mdi:lock$$'}
    '&kp LG(L)': {t: '$$mdi:lock$$'}
    '&kp C_SLEEP': {t: '$$mdi:sleep$$'}
    '&kp C_MUTE': {t: '$$mdi:volume-mute$$'}
    '&kp C_PP': {t: '$$mdi:play-pause$$'}
    '&kp C_PREV': {t: '$$mdi:skip-previous$$'}
    '&kp C_NEXT': {t: '$$mdi:skip-next$$'}
    '&kp LG(F9)': {t: '$$mdi:microphone-off$$'}
    '&kp LG(COMMA)': {t: Space ←}
    '&kp LG(DOT)': {t: Space →}
    '&kp LG(LS(T))': {t: Pin Win}
    '&kp LG(LA(S))': {t: STT}
    '&bootloader': {t: '$$mdi:progress-download$$', s: Boot}
    '&sys_reset': {t: '$$mdi:restart$$', s: Reset}
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: ⌃
    right_ctrl: ⌃
    left_shift: '$$mdi:arrow-up-bold$$'
    right_shift: '$$mdi:arrow-up-bold$$'
    left_alt: ⌥
    right_alt: ⌥
    left_gui: ❖
    right_gui: ❖
    keycode_combiner: '{mods}{key}'
    mod_combiner: '{mod_1}{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    BACKSPACE: '$$mdi:backspace$$'
    BSPC: '$$mdi:backspace$$'
    DELETE: '$$mdi:backspace-reverse$$'
    DEL: '$$mdi:backspace-reverse$$'
    TAB: '$$mdi:keyboard-tab$$'
    RETURN: '$$mdi:keyboard-return$$'
    RET: '$$mdi:keyboard-return$$'
    ENTER: '$$mdi:keyboard-return$$'
    ESCAPE: '$$mdi:keyboard-esc$$'
    ESC: '$$mdi:keyboard-esc$$'
    SPACE: '$$mdi:keyboard-space$$'
    SPC: '$$mdi:keyboard-space$$'
    UP: '$$mdi:arrow-up$$'
    DOWN: '$$mdi:arrow-down$$'
    LEFT: '$$mdi:arrow-left$$'
    RIGHT: '$$mdi:arrow-right$$'
    HOME: '$$mdi:arrow-collapse-left$$'
    END: '$$mdi:arrow-collapse-right$$'
    PAGE_UP: PgUp
    PG_UP: PgUp
    PAGE_DOWN: PgDn
    PG_DN: PgDn
    LSHIFT: '$$mdi:arrow-up-bold$$'
    LSHFT: '$$mdi:arrow-up-bold$$'
    RSHIFT: '$$mdi:arrow-up-bold$$'
    RSHFT: '$$mdi:arrow-up-bold$$'
    LCTRL: ⌃
    LALT: ⌥
    LGUI: ❖
    RCTRL: ⌃
    RALT: ⌥
    RGUI: ❖
    CAPSLOCK: Caps
    CAPS: Caps
  zmk_combos:
    combo_tab: {key: {t: '$$mdi:keyboard-tab$$'}}
    combo_bspc: {key: {t: '$$mdi:backspace$$', s: '$$mdi:backspace-reverse$$'}}
    combo_undo_redo: {key: {t: '$$mdi:undo$$', s: '$$mdi:redo$$'}}
    combo_ccp: {key: {t: '$$mdi:content-copy$$'}}
    combo_lpar: {key: {t: '('}}
    combo_rpar: {key: {t: ')'}}
    combo_lbkt: {key: {t: '['}}
    combo_lbrc: {key: {t: '{'}}
    combo_combo_lt: {key: {t: '<'}}
    combo_rbkt: {key: {t: ']'}}
    combo_rbrc: {key: {t: '}'}}
    combo_combo_gt: {key: {t: '>'}}
    combo_shcha: {key: {t: Щ}}
    combo_hard_sign: {key: {t: Ъ/Ї}}
    combo_yo_apos: {key: {t: Ё/'}}
    combo_v_comma_excl: {key: {t: ',', s: '!'}}
    combo_v_dot_qmark: {key: {t: '.', s: '?'}}
    combo_v_dquote: {key: {t: '"'}}
    combo_v_colon: {key: {t: ':'}}
    combo_v_semi: {key: {t: ;}}
    combo_system_combo: {key: {t: Magic}}
    combo_mouse_combo: {key: {t: Mouse}}
    combo_caps: {key: {t: CapsWrd, s: CapsLck}}
    combo_fn_combo: {key: {t: Fn}}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes:
    - .cache
