draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  footer_text: ''
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  glyph_urls:
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    tabler: https://raw.githubusercontent.com/tabler/tabler-icons/master/icons/outline/{}.svg
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    '&sqt_dqt': {t: '''', s: '"'}
    '&minus_slash': {t: '-', s: '/'}
    '&dot_qmark': {t: '.', s: '?'}
    '&comma_excl': {t: ',', s: '!'}
    '&bspc_del': {t: '$$mdi:backspace$$', s: '$$mdi:backspace-reverse$$'}
    '&undo_redo': {t: '$$mdi:undo$$', s: '$$mdi:redo$$'}
    '&copy_cut': {t: '$$mdi:content-copy$$', s: '$$mdi:content-cut$$'}
    '&v_comma_excl': {t: ',', s: '!'}
    '&v_dot_qmark': {t: '.', s: '?'}
    '&thumb_bspc LSHFT 0': {t: '$$mdi:backspace$$', h: '$$mdi:arrow-up-bold$$', s: '$$mdi:backspace-reverse$$'}
    '&nav_ht LAYER_Nav 0': {t: '$$mdi:keyboard-esc$$', h: Nav, s: '$$mdi:keyboard-tab$$'}
    '&thumb_spc LAYER_Symbol SPACE': {t: '$$mdi:keyboard-space$$', h: Symbol}
    '&lt LAYER_Num RET': {t: '$$mdi:keyboard-return$$', h: Num}
    '&tog LAYER_Mouse': {t: Mouse, type: layer-activator}
    '&mouse_ht LAYER_Mouse LAYER_Mouse': {t: Mouse, type: layer-activator}
    '&to_graphite': {t: Graphite, type: layer-activator}
    '&to_racket': {t: Racket, type: layer-activator}
    '&to_duskwp': {t: Dusk, type: layer-activator}
    '&alpha_magic_dusk_1': {t: '$$mdi:star-four-points$$'}
    '&nav_bspc LAYER_Nav 0': {t: '$$mdi:backspace$$', h: Nav, s: '$$mdi:backspace-reverse$$'}
    '&spc_sft LSHFT SPACE': {t: '$$mdi:keyboard-space$$', h: '$$mdi:arrow-up-bold$$'}
    '&repeat_sym LAYER_Symbol 0': {t: '$$mdi:repeat$$', h: Symbol}
    '&thumb_r LAYER_NumMirror R': {t: R, h: NumMirror}
    '&thumb_r LAYER_NumMirror C': {t: C, h: NumMirror}
    '&thumb_r LAYER_Symbol R': {t: R, h: Symbol}
    '&thumb_r LAYER_Symbol C': {t: C, h: Symbol}
    '&thumb_r LAYER_Symbol S': {t: S, h: Symbol}
    '&nav_repeat LAYER_Nav 0': {t: '$$mdi:repeat$$', h: Nav}
    '&thumb_magic_1 LSHFT 0': {t: '$$mdi:repeat$$', h: '$$mdi:arrow-up-bold$$'}
    '&thumb_magic_2 LSHFT 0': {t: '$$mdi:repeat$$', h: '$$mdi:arrow-up-bold$$'}
    '&alpha_magic_racket_1': {t: '$$mdi:star-four-points$$'}
    '&alpha_magic_neirox_1': {t: '$$mdi:star-four-points$$'}
    '&sl LAYER_Fn': {t: Fn}
    '&sl LAYER_Magic': {t: System, type: layer-activator}
    '&soft_off': {t: '$$mdi:keyboard-off-outline$$'}
    '&fslh_colon': {t: '/', s: ':'}
    '&mkp LCLK': LMB
    '&mkp RCLK': RMB
    '&mkp MCLK': MMB
    '&mkp MB4': MB4
    '&mkp MB5': MB5
    '&mmv MOVE_UP': "Mouse ↑"
    '&mmv MOVE_DOWN': "Mouse ↓"
    '&mmv MOVE_LEFT': "Mouse ←"
    '&mmv MOVE_RIGHT': "Mouse →"
    '&msc SCRL_UP': "Scroll ↑"
    '&msc SCRL_DOWN': "Scroll ↓"
    '&msc SCRL_LEFT': "Scroll ←"
    '&msc SCRL_RIGHT': "Scroll →"
    '&lang_en': {t: EN}
    '&lang_ru': {t: RU}
    '&bt_0': {t: BT 0}
    '&bt_1': {t: BT 1}
    '&bt_2': {t: BT 2}
    '&bt_3': {t: BT 3}
    '&kp LC(LS(TAB))': {t: Tab ←}
    '&kp LC(TAB)': {t: Tab →}
    '&kp LC(Z)': {t: Undo}
    '&kp LC(LS(Z))': {t: Redo}
    '&kp LC(A)': {t: Tmux}
    '&kp _SCR_AREA': {t: '$$mdi:crop$$', s: Scr}
    '&kp _SCR_FULL': {t: '$$mdi:monitor-screenshot$$', s: Scr}
    '&kp _SHUTDOWN': {t: '$$mdi:power$$'}
    '&kp LG(LC(LS(Q)))': {t: '$$mdi:power$$'}
    '&kp C_POWER': {t: '$$mdi:power$$'}
    '&kp K_POWER': {t: '$$mdi:power$$'}
    '&kp _LOCK': {t: '$$mdi:lock$$'}
    '&kp LG(LS(L))': {t: '$$mdi:lock$$'}
    '&kp LG(L)': {t: '$$mdi:lock$$'}
    '&kp C_SLEEP': {t: '$$mdi:moon-waning-crescent$$'}
    '&kp C_MUTE': {t: '$$mdi:volume-mute$$'}
    '&kp C_PP': {t: '$$mdi:play-pause$$'}
    '&kp C_PREV': {t: '$$mdi:skip-previous$$'}
    '&kp C_NEXT': {t: '$$mdi:skip-next$$'}
    '&kp LG(F9)': {t: '$$mdi:microphone-off$$'}
    '&kp LG(O)': {t: Space ←}
    '&kp LG(U)': {t: Space →}
    '&kp LG(LA(S))': {t: STT}
    '&bootloader': {t: '$$mdi:progress-download$$', s: Boot}
    '&sys_reset': {t: '$$mdi:restart$$', s: Reset}
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: ⌃
    right_ctrl: ⌃
    left_shift: '$$mdi:arrow-up-bold$$'
    right_shift: '$$mdi:arrow-up-bold$$'
    left_alt: ⌥
    right_alt: ⌥
    left_gui: ❖
    right_gui: ❖
    keycode_combiner: '{mods}{key}'
    mod_combiner: '{mod_1}{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  zmk_remove_keycode_prefix: []
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    BACKSPACE: '$$mdi:backspace$$'
    BSPC: '$$mdi:backspace$$'
    DELETE: '$$mdi:backspace-reverse$$'
    DEL: '$$mdi:backspace-reverse$$'
    TAB: '$$mdi:keyboard-tab$$'
    RETURN: '$$mdi:keyboard-return$$'
    RET: '$$mdi:keyboard-return$$'
    ENTER: '$$mdi:keyboard-return$$'
    ESCAPE: '$$mdi:keyboard-esc$$'
    ESC: '$$mdi:keyboard-esc$$'
    SPACE: '$$mdi:keyboard-space$$'
    SPC: '$$mdi:keyboard-space$$'
    UP: '$$mdi:arrow-up$$'
    DOWN: '$$mdi:arrow-down$$'
    LEFT: '$$mdi:arrow-left$$'
    RIGHT: '$$mdi:arrow-right$$'
    HOME: '$$mdi:arrow-collapse-left$$'
    END: '$$mdi:arrow-collapse-right$$'
    PAGE_UP: '$$mdi:arrow-collapse-up$$'
    PG_UP: '$$mdi:arrow-collapse-up$$'
    PAGE_DOWN: '$$mdi:arrow-collapse-down$$'
    PG_DN: '$$mdi:arrow-collapse-down$$'
    LSHIFT: '$$mdi:arrow-up-bold$$'
    LSHFT: '$$mdi:arrow-up-bold$$'
    RSHIFT: '$$mdi:arrow-up-bold$$'
    RSHFT: '$$mdi:arrow-up-bold$$'
    LCTRL: ⌃
    LALT: ⌥
    LGUI: ❖
    RCTRL: ⌃
    RALT: ⌥
    RGUI: ❖
    CAPSLOCK: Caps
    CAPS: Caps
  zmk_combos:
    combo_undo_redo: {key: {t: '$$mdi:undo$$', s: '$$mdi:redo$$'}}
    combo_qm_paste: {key: {t: '$$mdi:content-paste$$'}}
    combo_mc_copy_cut: {key: {t: '$$mdi:content-copy$$', s: '$$mdi:content-cut$$'}}
    combo_shcha: {key: {t: Щ}}
    combo_hard_sign: {key: {t: Ъ/Ї}}
    combo_yo_apos: {key: {t: Ё/'}}
    combo_v_comma_excl: {key: {t: ',', s: '!'}}
    combo_v_dot_qmark: {key: {t: '.', s: '?'}}
    combo_system_combo: {key: {t: System}}
    combo_mouse_combo: {key: {t: Mouse}}
    combo_caps: {key: {t: CapsWrd, s: CapsLck}}
    combo_fn_combo: {key: {t: Fn}}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes:
    - .cache
