manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: rzssh
      url-base: https://github.com/rzssh
    - name: zzeneg
      url-base: https://github.com/zzeneg

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-leader-key
      remote: urob
      revision: main
    - name: zmk-adaptive-key
      remote: rzssh
      revision: skipmagic
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-component-underdongle
      remote: rzssh
      revision: main
    - name: zmk-raw-hid
      remote: zzeneg
      revision: main

    - name: zmk-tri-state
      remote: urob
      revision: main

  self:
    path: config
