USER_NAME := razen

BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LTO_ENABLE = yes
MAGIC_ENABLE = no
NKRO_ENABLE = no
SPACE_CADET_ENABLE = no
