manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: rzssh
      url-base: https://github.com/rzssh

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import:
        file: app/west.yml
        path-prefix: ""
    - name: zmk-helpers
      remote: urob
      revision: main
      path: modules/zmk/helpers
    - name: zmk-adaptive-key
      remote: rzssh
      revision: skipmagic
      path: modules/zmk/adaptive-key

  self:
    path: config
