manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: r4zendev
      url-base: https://github.com/r4zendev

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
    - name: zmk-leader-key
      remote: urob
      revision: main
    - name: zmk-adaptive-key
      remote: r4zendev
      revision: skipmagic
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main

  self:
    path: config
