[graphite]
enabled = false
timeout_ms = 1000
swaps = [
  ["S", "C", "D"],
  ["P", "H", "N"],
  ["C", "S", "X"],
  ["U", "E", "O"],
  ["W", "S", "G"],
  ["S", "W", "V"],
  ["R", "L", "W"],

  # ["B", "R", "D"],
  # ["M", "B", "C"],

  # ["R", "L", "Z"],
  # ["W", "S", "Z"],
  # ["S", "W", "SQT"],
  # ["P", "Y", "Z"],
  # ["F", "Y", "Z"],
  # ["H", "Y", "Z"],
  # ["K", "Y", "Z"],
]

[dusk]
enabled = false
timeout_ms = 1000
swaps = [
  ["U", "O", "E"],
  ["SQT", "O", "L"],
  ["SQT", "U", "M"],
]
