[graphite]
timeout_ms = 1000
swaps = [
  ["S", "C", "D"],
  ["P", "H", "N"],
  ["C", "S", "X"],
  ["U", "E", "O"],
  ["W", "S", "G"],
  ["S", "W", "V"],
  ["R", "L", "W"],

  # ["B", "R", "D"],
  # ["M", "B", "C"],

  # ["R", "L", "Z"],
  # ["W", "S", "Z"],
  # ["S", "W", "SQT"],
  # ["P", "Y", "Z"],
  # ["F", "Y", "Z"],
  # ["H", "Y", "Z"],
  # ["K", "Y", "Z"],
]

[dusk]
timeout_ms = 1000
swaps = [
  ["U", "O", "E"],
  ["SQT", "O", "L"],
  ["SQT", "U", "M"],
]

[night]
timeout_ms = 1000
swaps = [
  ["U", "O", "E"],
]

[twirl]
timeout_ms = 1000
swaps = [
  ["S", "D", "C"],
  ["P", "Q", "T"],
  ["R", "Q", "L"],
  ["G", "P", "S"],
  ["N", "H", "G"],
]

[whirlie]
timeout_ms = 1000
swaps = [
  ["S", "D", "C"],
  ["R", "J", "Y"],
  ["L", "J", "Y"],
  ["P", "Q", "T"],
  ["R", "Q", "L"],
  ["G", "P", "S"],
  ["N", "H", "G"],
]

[whirlmrl]
timeout_ms = 1000
swaps = [
  ["S", "D", "C"],
  ["R", "W", "L"],
  ["P", "F", "T"],
  ["G", "P", "S"],
  ["N", "H", "G"],
  ["R", "H", "M"],
]

[whirly]
timeout_ms = 1000
swaps = [
  ["S", "D", "C"],
  ["R", "X", "L"],
  ["G", "P", "S"],
  ["N", "H", "G"],
]
