#!/usr/bin/env python3
"""Generate ZMK adaptive-swap behaviors from the shared swap table."""

from __future__ import annotations

import argparse
import re
from collections import OrderedDict
from pathlib import Path


SOURCE = Path("config/includes/adaptive_swaps.dtsi")
OUTPUT = Path("config/includes/generated/adaptive_swaps.dtsi")

GRAPHITE_HOLD_TAPS = {
    "N": ("graphite_hml_n", "LGUI", "KEYS_R"),
    "R": ("graphite_hml_r", "LALT", "KEYS_R"),
    "S": ("graphite_hml_s", "LSHFT", "KEYS_R"),
    "H": ("graphite_hmr_h", "RSHFT", "KEYS_L"),
    "E": ("graphite_hmr_e", "RALT", "KEYS_L"),
}


def strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    return "\n".join(line.split("//", 1)[0] for line in text.splitlines())


def parse_swaps(path: Path) -> list[tuple[str, str, str, str]]:
    text = strip_comments(path.read_text())
    swaps: list[tuple[str, str, str, str]] = []
    seen: set[tuple[str, str, str, str]] = set()
    pattern = re.compile(
        r"ADAPTIVE_SWAP\(\s*([A-Za-z][A-Za-z0-9_]*)\s*,\s*"
        r"([A-Z][A-Z0-9_]*)\s*,\s*([A-Z][A-Z0-9_]*)\s*,\s*"
        r"([A-Z][A-Z0-9_]*)\s*\)"
    )

    for match in pattern.finditer(text):
        layer, prior, left, right = match.groups()
        if layer != "Graphite":
            raise ValueError(f"Unsupported adaptive swap layer: {layer}")
        if left == right:
            raise ValueError(f"Adaptive swap cannot map {left} to itself")
        item = (layer, prior, left, right)
        inverse = (layer, prior, right, left)
        if item in seen or inverse in seen:
            raise ValueError(f"Duplicate adaptive swap after {prior}: {left} <-> {right}")
        seen.add(item)
        swaps.append(item)

    if not swaps:
        raise ValueError(f"No ADAPTIVE_SWAP entries found in {path}")

    return swaps


def label_key(key: str) -> str:
    return key.lower()


def generate_graphite(swaps: list[tuple[str, str, str, str]]) -> str:
    groups: OrderedDict[str, list[tuple[str, str]]] = OrderedDict()
    for _layer, prior, left, right in swaps:
        groups.setdefault(right, []).append((prior, left))
        groups.setdefault(left, []).append((prior, right))

    out = [
        "/* Generated by scripts/generate_adaptive_swaps.py; edit config/includes/adaptive_swaps.dtsi. */",
        "",
        "#if GRAPHITE_BIGRAM_SWAPS",
        "",
    ]

    for key, triggers in groups.items():
        out.append(f"ZMK_ADAPTIVE_KEY(graphite_bigram_{label_key(key)}, bindings = <&kp {key}>;")
        for prior, output in triggers:
            out.append(
                f"    graphite_bigram_{label_key(prior)}{label_key(output)} "
                f"{{ trigger-keys = <{prior}>; max-prior-idle-ms = <GRAPHITE_BIGRAM_TIMEOUT_MS>; "
                f"bindings = <&kp {output}>; strict-modifiers; }};"
            )
        out.append(")")
        out.append("")

    hold_tap_keys = [key for key in groups if key in GRAPHITE_HOLD_TAPS]
    if hold_tap_keys:
        for key in hold_tap_keys:
            name, _mod, trigger_keys = GRAPHITE_HOLD_TAPS[key]
            out.extend(
                [
                    f"ZMK_HOLD_TAP({name}, bindings = <&kp>, <&graphite_bigram_{label_key(key)}>;",
                    '             flavor = "balanced"; tapping-term-ms = <180>;',
                    "             quick-tap-ms = <QUICK_TAP_MS>; require-prior-idle-ms = <100>;",
                    f"             hold-trigger-key-positions = <{trigger_keys} THUMBS>;",
                    "             hold-trigger-on-release;)",
                    "",
                ]
            )

    for key in groups:
        if key in GRAPHITE_HOLD_TAPS:
            name, mod, _trigger_keys = GRAPHITE_HOLD_TAPS[key]
            out.append(f"#define GRAPHITE_{key} &{name} {mod} 0")
        else:
            out.append(f"#define GRAPHITE_{key} &graphite_bigram_{label_key(key)}")

    out.extend(["", "#endif", ""])
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path.cwd())
    parser.add_argument("--out", type=Path)
    args = parser.parse_args()

    repo = args.repo.resolve()
    source = repo / SOURCE
    output = args.out or repo / OUTPUT

    swaps = parse_swaps(source)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(generate_graphite(swaps))


if __name__ == "__main__":
    main()
