#pragma once

#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY
#define QUICK_TAP_TERM 175
#define FLOW_TAP_TERM 100
#define PERMISSIVE_HOLD_PER_KEY
#define CHORDAL_HOLD
#define ONESHOT_TIMEOUT 1200
#define ONESHOT_TAP_TOGGLE 0

#define COMBO_TERM 30
#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250
#define COMBO_TERM_PER_COMBO
#define COMBO_SHOULD_TRIGGER
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_MOVE_DELTA 16
#define MOUSEKEY_MAX_SPEED 8
#define MOUSEKEY_TIME_TO_MAX 40
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 16
#define MOUSEKEY_WHEEL_MAX_SPEED 4
#define MOUSEKEY_WHEEL_TIME_TO_MAX 40

#define MASTER_RIGHT
#define I2C_DRIVER I2CD1
#define OLED_DISPLAY_ADDRESS 0x3C
#define OLED_IC OLED_IC_SH1107
