BOOTMAGIC_ENABLE = no
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
GRAVE_ESC_ENABLE = no
HAPTIC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LTO_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
MUSIC_ENABLE = no
NKRO_ENABLE = no
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
RGB_MATRIX_ENABLE = yes
SPACE_CADET_ENABLE = no

ifneq ($(strip $(OPERATING_SYSTEM)),)
    OPT_DEFS += -DOPERATING_SYSTEM=$(OPERATING_SYSTEM)
endif
