name: Build Sweep

on: [push, pull_request, workflow_dispatch]

jobs:
  left:
    uses: ./.github/workflows/base.build.yml
    with:
      manifest: cradio.west.yml
      board: nice_nano
      shield: cradio_left
  right:
    uses: ./.github/workflows/base.build.yml
    with:
      manifest: cradio.west.yml
      board: nice_nano
      shield: cradio_right
