name: Build Sweep

on: [push, pull_request, workflow_dispatch]

jobs:
  left:
    uses: ./.github/workflows/base.build.yml
    with:
      manifest: cradio.west.yml
      board: nice_nano/nrf52840/zmk
      shield: cradio_left
  right:
    uses: ./.github/workflows/base.build.yml
    with:
      manifest: cradio.west.yml
      board: nice_nano/nrf52840/zmk
      shield: cradio_right
  merge:
    needs: [left, right]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: sweep
          pattern: artifact-*
          delete-merged: true
