name: Build Glove80

on: [push, pull_request, workflow_dispatch]

jobs:
  left:
    uses: ./.github/workflows/base.build.yml
    with:
      manifest: glove80.west.yml
      board: glove80_lh
  right:
    uses: ./.github/workflows/base.build.yml
    with:
      manifest: glove80.west.yml
      board: glove80_rh
  merge:
    needs: [left, right]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: glove80
          pattern: artifact-*
          delete-merged: true
