name: Build LambBT

on: [push, pull_request, workflow_dispatch]

jobs:
  left:
    uses: ./.github/workflows/base.build.yml
    with:
      keyboard: lambbt
      board: nice_nano/nrf52840/zmk
      shield: lambbt_left
  right:
    uses: ./.github/workflows/base.build.yml
    with:
      keyboard: lambbt
      board: nice_nano/nrf52840/zmk
      shield: lambbt_right
  merge:
    needs: [left, right]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: lambbt
          pattern: artifact-*
          delete-merged: true
