name: Build Piantor Pro

on: [push, pull_request, workflow_dispatch]

jobs:
  left:
    uses: ./.github/workflows/base.build.yml
    with:
      keyboard: piantor_pro
      board: rpi_pico/rp2040/zmk
      shield: piantor_pro_left
  right:
    uses: ./.github/workflows/base.build.yml
    with:
      keyboard: piantor_pro
      board: rpi_pico/rp2040/zmk
      shield: piantor_pro_right
  merge:
    needs: [left, right]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: piantor_pro
          pattern: artifact-*
          delete-merged: true
