name: Build Aurora Sweep

on: [push, pull_request, workflow_dispatch]

jobs:
  left:
    uses: ./.github/workflows/base.build.yml
    with:
      keyboard: splitkb_aurora_sweep
      board: nice_nano/nrf52840/zmk
      shield: splitkb_aurora_sweep_left
  right:
    uses: ./.github/workflows/base.build.yml
    with:
      keyboard: splitkb_aurora_sweep
      board: nice_nano/nrf52840/zmk
      shield: splitkb_aurora_sweep_right
  merge:
    needs: [left, right]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@v4
        with:
          name: aurora_sweep
          pattern: artifact-*
          delete-merged: true
